### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by duvivier**
Updating Readme.md files for repositories

Developer(s): Alice DuVivier

Please suggest code Pull Request reviewers in the column at right.

Are the code changes bit for bit, different at roundoff level, or more substantial? bit for bit

Is the documentation being updated with this PR? (Y/N) N
If not, does the documentation need to be updated separately at a later time? (Y/N) N
Note: "Documentation" includes information on the wiki and .rst files in doc/source/,
which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/.

Other Relevant Details:  I know this is not a bug fix but it's based on our discussions of updating the readme.md files for the repos. 

See the rendered file at: https://github.com/duvivier/CICE-svn-trunk/blob/newreadme/README.md

### CODE REVIEW

**Review by eclare108213 — COMMENTED** [review]
Are the instructions about svn tags now being branches and how to get get them available somewhere else?  This is different from the CICE and Icepack repos, so perhaps we should keep it here, or put it on the wiki, or otherwise provide a bit more of a hint how to deal with this repo in particular.  Perhaps make a special wiki page in this repo, and link to it from the Resources index?

**Comment by duvivier** [comment]
Ok, I made the change to the Readme.md and added the following wiki page:
https://github.com/CICE-Consortium/CICE-svn-trunk/wiki/Obtaining-CICE-pre-version-6

**Review by apcraig — APPROVED** [review]
In the README.md, I would phrase this a little different,

"If you expect to make any changes to the code, we recommend that you work in the CICE and Icepack repositories. Changes made to code in this repository will not be accepted, other than critical bug fixes."

I would be a little more direct, something more like 

"This repository is frozen, all development has moved to the Icepack and CICE v6 repositories".  

You could have links or not, and maybe even combine with the sentence above, but I think we want to be clear about the status of this repo.

**Comment by apcraig** [comment]
Also note that somehow, this change has a conflict.  Not sure what's going on there.

**Comment by duvivier** [comment]
Tony, I made the change you suggest to be more direct. I also noticed that there is a conflict but when I looked at "Resolve conflicts" it wasn't really useful as it's just text that has changed.

**Comment by apcraig** [comment]
Thanks Alice, looks good.

**Comment by eclare108213** [comment]
I don't know what to do with the conflict, so I'm going to try to edit the README.md directly, inserting Alice's changes.

**Comment by eclare108213** [comment]
Edited directly.

**Pull request closed without merging**
